### ISSUE TITLE
Postal code should be VARCHAR

### ISSUE THREAD

**Issue by shayanabbas** [CrewHRM/CrewHRM#100]
Right now if i add `00100` in postal code it strips the 00 in the beginning, its been set to integer where as in many region postal code could be in alphabets as well.

**Comment by sh-sabbir** [comment]
Hello @shayanabbas I tried to reproduce this problem. But couldn't. Please add the steps to reproduce the issue. If possible add a screen recording too

**Comment by shayanabbas** [comment]
Create a new job post `wp-admin/admin.php?page=crewhrm-all-jobs#/dashboard/jobs/editor/new/`

add a job post with postal code `00100`

<img width="733" alt="Screenshot 2024-09-22 at 14 45 47" src="https://github.com/user-attachments/assets/cb595228-92d2-4b93-b9c3-4d5145a72b0f">

and then when you can on frontend or check the job post even in backend it removes `00` from the start.

<img width="441" alt="Screenshot 2024-09-22 at 14 47 03" src="https://github.com/user-attachments/assets/aa7e1049-c9ab-40f3-acda-17d9dc1400e1">

**Comment by sh-sabbir** [comment]
Thanks. Fixed. Will be released with next update
