### ISSUE TITLE
Move attachment feature to pro version

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#19]
The setting should also move. We should refine the settings fields in a more human-friendly way. The file size limit option should be the largest allowed for each file and the number of files allowed per application. So, if we allow 3MB per file and a maximum of 3 attachments with a resume and cover letter, it would be 3x3 + 2x3 = 15MB per applicant.

We should also display this information on the application form that the maximum file limit is this and this many files allowed. If you want to share larger files, upload them to Google Drive or some other file-sharing platform and add the link to the cover letter or resume.

**Comment by jayedul** [comment]
Done
