### ISSUE TITLE
Update disabled file type text color

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#24]
<img width="429" alt="image" src="https://github.com/CrewHRM/CrewHRM/assets/3262638/23af8c4d-bd05-4ce1-85f6-032f6b87ab99">
The input fields are disabled, but the text stays black. This might create confusion among users and result in frustrated support emails. Please match the text. I have done one with inspect element to help you understand.

**Comment by jayedul** [comment]
Attachment and it's functionalities have been moved to pro as an add-on. There's no disabled option now.
