### ISSUE TITLE
Show messages after installation to set permalink to post name and a page to display job posts

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#28]
If I do not set a page showing job posts in the settings, I get a 404 error. Also, the preview link needs to be fixed after publishing the job post.

The message should be an info message and use the default WordPress style. It should say-
Please set up a page to display the job posts. The word set page will be a link and will take the user to the job listing settings screen.
This is the link I am talking about. /wp-admin/admin.php?page=crewhrm-settings#/settings/recruitment/careers/
It would be great if we could highlight the option to better direct users' attention. When we click on a comment notification on Facebook, it highlights the comment that we got notified about.

----

I am unsure if we need to flush the permalink for the plugin to work correctly. If that is needed, we should also show a message with link.

**Comment by jayedul** [comment]
Done. Permalink gets flushed automatically after saving settings.
