### ISSUE TITLE
Job posts do not load in FSE themes

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#29]
I think this might be a template-related issue. Please test the plugin in The Twenty-Three theme. I got a 404 error with this theme.

Please record a small video if people need to create a custom template with some code or shortcode. I will convert that into documentation

**Comment by jayedul** [comment]
It works here. I guess saving the permalink again in settings page might resolve the issue.

**Comment by sekanderb** [comment]
Okay. I think we can close this for now as we do not have enough data about the possible causes and settings as I have tested alone.
