### ISSUE TITLE
Sync dropdown and expandable search field styles with design

### ISSUE THREAD

**Issue by jayedul** [CrewHRM/CrewHRM#37]
Create multiple design variation and apply based on props argument. 

<img width="842" alt="Screenshot 2023-10-23 at 2 54 36 PM" src="https://github.com/CrewHRM/CrewHRM/assets/12506700/acff8e43-b493-4795-9e12-b12f740ef715">

<img width="1002" alt="Screenshot 2023-10-23 at 2 55 25 PM" src="https://github.com/CrewHRM/CrewHRM/assets/12506700/27f034e0-2509-4eef-9c9b-ef48664b08cf">

<img width="999" alt="Screenshot 2023-10-23 at 2 56 10 PM" src="https://github.com/CrewHRM/CrewHRM/assets/12506700/45969a58-6fca-44a5-afd4-b6f3bb514d4c">

**Comment by iamsaief** [comment]
[PR : Sync dropdown and expandable search field styles with design #37 ](https://github.com/CrewHRM/CrewHRM/pull/43)
Modified Material components are pushed to main branch `Materials > main `

**Comment by jayedul** [comment]
Done
