### ISSUE TITLE
Gutenberg blocks and short-codes

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#42]
1. Show job posts with filters
2. Show job posts on specific category and option to limit results
3. Show job post of a specific type like all remote jobs, all on site jobs etc

You can create more combinations if you like.

**Comment by jayedul** [comment]
Both are implemented now. Gutenberg block has settings panel. However shortcode will support the following attributes

- **search:** `true/false` to show/hide search field
- **header:** `true/false` to show/hide the header
- **hero_image_url:** Header image URL
- **tagline:** Tagline text for the header
- **sidebar:** `true/false` to show/hide sidebar
- **department_id:** The department ID to show jobs from
- **keyword:** The keyword to show certain jobs that matches the keyword
- **country_code:** Two digit country code to show jobs for
- **employment_type:** `full_time/part_time/contract/temporary/trainee` for showing specific job types
