### ISSUE TITLE
send email notification after applying to the job

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#44]
after applying to a job post, it says thank you for applying to the job... you will receive email confirmation. but no email is sent. even if the pro email addon is activated.

**Comment by sekanderb** [comment]
Here is the email text-

Hi {applicant first name}!

Thank you for being so interested in joining {company name}! 

We have received your application documents and will now carefully check them! We make every effort to ensure that our emails are sent and delivered on time. If, in a few days, you still don't see our reply with the next steps of your application, please check your 'spam' or 'junk mail' folder and add '{primary email}' to your 'White List' or 'Safe Sender List'.

Thank you!

**Comment by jayedul** [comment]
Done

**Comment by jayedul** [comment]
Make sure the event is enabled in settings first.
