### ISSUE TITLE
Promote Pro features

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#47]
### High priority
- [x]  Add-on screen design
- [x]  Add email settings - free and pro both. Free will have only application received confirmation for the applicant. Pro will add more options like the screenshot below.

### Low Priority
- [x] Calendar - upgrade pro message
- [x]  Meeting schedule - upgrade pro message
- [x]  Comment - upgrade pro message
- [x]  Attachment settings - upgrade pro message
- [x]  Google Meet and Zoom Settings - upgrade pro message
- [x]  Dashboard calendar widget - upgrade pro message

The email settings will be the same as the attachment settings. Here is what it would look like
<img width="560" alt="Screenshot 2023-10-28 at 6 02 44 PM" src="https://github.com/CrewHRM/CrewHRM/assets/3262638/c13e1f9f-83a0-4c08-a424-cc0b6d2d6a08">

Please add the elements without functionality to the free version for now. We will add the blockers after we get the design.
The first two are priority. After these are done, we will do the rest one by one.

### Here is the relevant text to copy-paste
Email Notifications
CrewHRM sends updates by email to admins and applicants. Turn them on as needed.

Application received confirmation email to applicants.

New job post published to primary email.

Meeting Invitation to candidates

Meeting invitation to hiring team members

New submission received to the primary email.

New submission received to the secondary email.

Candidate moved to a stage notification to the primary email

Hiring stage progress email to the candidate

**Comment by jayedul** [comment]
Done
