### ISSUE TITLE
Add welcome screen - show after activating the plugin

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#49]
https://www.figma.com/file/L2YGgx2uXPaWxrcI4c1tag/Crew-HRM?type=design&node-id=2802-18022&mode=design&t=SnTwpwQ4FGnKgM3U-4

This screen should show after the plugin is activated. Here are the links-

1. https://www.youtube.com/@crewhrm
2. https://www.facebook.com/crewhrm
3. https://twitter.com/crewhrm
4. https://www.facebook.com/groups/crewhrm
5. https://www.linkedin.com/company/crewhrm/

**Comment by jayedul** [comment]
Done
