### ISSUE TITLE
Date picker not working for new job posts

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#60]
When I try to insert the submission deadline on a new job post, it does not work. The field stays blank and I get these messages on the console https://prnt.sc/BKF_A2AHtiWp

**Comment by sekanderb** [comment]
If we are not showing the application deadline anywhere, please display it before the apply button like
Application Deadline: 30 June 2023

**Comment by jayedul** [comment]
Date picker fixed and deadline added. 
<img width="658" alt="Screenshot 2024-01-02 at 11 09 40 PM" src="https://github.com/CrewHRM/CrewHRM/assets/12506700/ea0a5c6e-1021-4bd9-91ec-2940ba38dd6b">
