### ISSUE TITLE
[BUG] Submission Deadline Can't be set up. 

### ISSUE THREAD

**Issue by telldaren** [CrewHRM/CrewHRM#63]
Submission deadline can't be set up either by picking a date in the calendar or manually typing dates.

![image](https://github.com/CrewHRM/CrewHRM/assets/73165985/f2e10d8b-e4a8-4b23-824f-37bd829abc49)

**Comment by jayedul** [comment]
This issue has been fixed meanwhile and pushed to main branch. It will be released in the next version.
