### ISSUE TITLE
[suggestion for better UX] Job listing (Current openings) page button and clickable area

### ISSUE THREAD

**Issue by telldaren** [CrewHRM/CrewHRM#64]
- [ ] Button copy can be changed from 'Apply' to 'View'. Would be great if admin can edit the copy as needed. 

- [ ] Would be better if the whole row can be clicked.  

![image](https://github.com/CrewHRM/CrewHRM/assets/73165985/f12c95bf-67dd-4c4c-9ddc-b29b2380928f)

**Comment by jayedul** [comment]
Button text was changed to `Details` meanwhile. Now the whole row has been made clickable. 
Will be released in the next version 1.0.6 soon.

**Comment by telldaren** [comment]
Looks awesome now!
