### ISSUE TITLE
[ISSUSE] Company Business Type is too limited

### ISSUE THREAD

**Issue by telldaren** [CrewHRM/CrewHRM#65]
It should have more options in the drop-down list, plus an option to add custom value. 

![image](https://github.com/CrewHRM/CrewHRM/assets/73165985/a08e8a38-1415-46a0-8f68-1614d710423f)

**Comment by jayedul** [comment]
The feature to add custom business type has been implemented, will be release in the next version 1.0.6 soon.


![Image](https://github.com/CrewHRM/CrewHRM/assets/12506700/af60d9a8-4472-468d-865f-f208e8f0879c)
