### ISSUE TITLE
Asking to solve captcha but it was not configured

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#68]
I have just activated the add-on but did not add any details to the settings for captcha verification. In ideal situation, the applicant should not receive any message about captcha.

The admin should receive a message that the captcha configuration is not finished yet.

How to reproduce the issue-
1. Activate the captcha add-on and leave the fields blank.
2. Try to submit a job application.

**Comment by jayedul** [comment]
Fixed.
