### ISSUE TITLE
Small php warning "undefined property" on PHP 8.1 & PHP 8.3

### ISSUE THREAD

**Issue by masteradhoc** [CrewHRM/CrewHRM#73]
Hi there

I get this small warning on every page in wp-admin:
`Warning: Undefined property: stdClass::$basename in ...\wp-content\plugins\hr-management-pro\classes\Setup\Updater.php on line 200`

Tested over Local, PHP 8.1 & PHP 8.3

Greets
Brian

**Comment by sekanderb** [comment]
Hello @masteradhoc,
I apologize for replying you late. Could you please share on which page you get the warning? A screenshot might help. I could not find the error on the admin pages.

**Comment by sh-sabbir** [comment]
This is no longer an issue
