### ISSUE TITLE
Translations do not work  on shortcode rendered content

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#75]
Steps to reproduce the issue-
1. Add the shortcode to a page.
2. Use loco translate and the auto translate add-on to translate the system into Bengali.
3. Visit the page with shortcode.

<img width="1167" alt="Screenshot 2024-03-07 at 4 17 20 PM" src="https://github.com/CrewHRM/CrewHRM/assets/3262638/9ae5d0ed-d9d1-447d-9753-a1081048c515">
<img width="1142" alt="Screenshot 2024-03-07 at 4 17 41 PM" src="https://github.com/CrewHRM/CrewHRM/assets/3262638/e418f9e4-d4b5-436d-bd59-912cc27b71ac">

**Comment by sh-sabbir** [comment]
Couldn't reproduce this issue. Followed these steps:

1. Installed "Loco Translate"
2. Installed "Auto translate add-on"
3. Translated the plugin using auto translate
4. Created a new page with "[crewhrm_careers]" shortcode
5. Changed site language to "Bengali"

This is what I see 

Without Shortcode:
![Image](https://github.com/CrewHRM/CrewHRM/assets/9151027/c71a175f-1f79-4974-83a0-2b7e0afcc17c)


With Shortcode:
![Image](https://github.com/CrewHRM/CrewHRM/assets/9151027/38323f4a-6f6b-41ac-a7de-3f78dc25d4bb)


The translation is working as intended. They are only missing a few strings in both cases. 
![Image](https://github.com/CrewHRM/CrewHRM/assets/9151027/eda5c0e5-316e-4215-a494-f499b3f8f033)

**Comment by sh-sabbir** [comment]
Fixed here: 543db3d
