### ISSUE TITLE
Departments created from settings do not load on the job post creating screen

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#78]
Steps to reproduce the issue-
1. Install the plugin on a fresh site.
2. Create some departments from the settings.
3. Go to create a new job post.
4. You will see the department dropdown does not show any department

But after adding a new department from the pop up on the job creating screen, the old ones come. The first one also gets duplicated.

**Comment by sekanderb** [comment]
I have added a department while creating the job post. Then, I went to edit the job post. The department vanished. But on the job listing page, it is showing and working properly.

**Comment by jayedul** [comment]
Fixed, it will be release in the next version 1.1.0
