### ISSUE TITLE
Can't save department from company settings

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#8]
it says saving failed. I get this message in console

<img width="1276" alt="Screenshot 2023-09-24 at 3 20 58 PM" src="https://github.com/CrewHRM/CrewHRM/assets/3262638/c20b471f-da2b-4f53-b164-ba19e3efab10">

**Comment by jayedul** [comment]
It'll work now. In fact it has been moved to settings and tested multiple times.
