### ISSUE TITLE
Performance enhancement

### ISSUE THREAD

**Issue by jayedul** [CrewHRM/CrewHRM#89]
Use transient to avoid repetitive plugin info parsing here in the function https://github.com/CrewHRM/CrewHRM/blob/main/classes/Helpers/_Array.php#L197-L228

And remove `$result = self::castRecursive( $result );` as it's not necessary in this context.

**Comment by sekanderb** [comment]
@sh-sabbir bhai, could you please confirm this is done?

**Comment by sh-sabbir** [comment]
@sekanderb Implemented. Closing with the next release...
