### ISSUE TITLE
Save wrong job salary

### ISSUE THREAD

**Issue by thanhpd56** [CrewHRM/CrewHRM#94]
Hello,
Whenever I create or update a job with salary 25000000 it  store and return job with strange number which is 16777215.
Please help. 
<img width="834" alt="image" src="https://github.com/user-attachments/assets/0ee8bb27-fda9-4d7d-a165-d818a7f232aa">

**Comment by sekanderb** [comment]
Hi,
We have fixed this issue on our new update for the free version of the plugin
